"""Weekly trading mandates for freestyle competitors.

Each freestyle competitor declares, once per week, the symbols it intends to
trade that week (its "mandate") plus an optional free-form strategy_config and a
plain-English rationale. The mandate is generated by the competitor's *own*
backend — its persona frames the pick — and persisted to `competitor_mandates`,
one row per (competitor, week_start = Monday).

The freestyle runner already reads this week's mandate via
`runner.competitor_universe()`, falling back to a WATCHLIST slice when none
exists, so a mandate is a pure enhancement — wiring this in is a drop-in.

A companion dynamic poller (`scripts/poll_competition.py`) polls the union of all
active mandates' symbols that lie *outside* the house WATCHLIST, so candle data
exists for whatever the competitors picked. The incumbent `poll_market.py` is
never touched.

$0 discipline: backend calls go through `helm.llm` (CLI mode — Claude
subscription / free gateways). No Anthropic API key is ever required.
"""

from __future__ import annotations

import json
from datetime import date, datetime, timedelta
from decimal import Decimal
from typing import Any
from zoneinfo import ZoneInfo

from helm.analytics.economics import book_economics
from helm.competition.backend import call_backend
from helm.competition.competitors import Competitor
from helm.config import TRADABLE_UNIVERSE, WATCHLIST
from helm.data.store import conn, insert_audit

IST = ZoneInfo("Asia/Kolkata")

# A mandate may name at most this many symbols (the brief's "≤ ~15").
MAX_MANDATE_SYMBOLS = 15
# Deterministic fallback size when a backend returns nothing valid.
FALLBACK_UNIVERSE_SIZE = 8

MANDATE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "universe": {"type": "array", "items": {"type": "string"}},
        "strategy_config": {"type": "object"},
        "rationale": {"type": "string"},
    },
    "required": ["universe", "rationale"],
}

SYSTEM_PROMPT_TEMPLATE = """You are an autonomous intraday trader entering a new \
trading week in a live paper-trading league against other AI agents. You trade \
NSE equities and ETFs intraday (MIS, square off same day) from your own isolated \
cash wallet.

YOUR PERSONA / EDGE:
{persona}

TASK — pick your watchlist for the week ahead:
- Choose AT MOST {max_symbols} symbols you will focus on this week.
- Choose ONLY from the candidate universe given in the snapshot — symbols not in \
that list are not tradable on this account and will be ignored.
- Pick names that genuinely fit YOUR edge and that you expect to give clean, \
liquid intraday moves. Fewer, well-chosen names beat a long generic list.
- Optionally include a small `strategy_config` object of numeric parameters you \
want to remember and trade by this week (e.g. {{"stop_atr": 1.5, "max_trades_per_day": 4}}).
- Give a one-paragraph `rationale` explaining the picks in plain English.

OUTPUT — strict JSON only, no prose, no markdown fences:
{{"universe": ["SYM", "SYM", ...], "strategy_config": {{...}}, \
"rationale": "why these names fit my edge this week"}}"""


def week_start(d: date) -> date:
    """Monday of the week containing `d` (mandates are keyed by week_start)."""
    return d - timedelta(days=d.weekday())


def current_week_start() -> date:
    return week_start(datetime.now(IST).date())


def next_week_start() -> date:
    """Monday of the NEXT calendar week (the upcoming trading week).

    Used by the weekend planner: a mandate written on Sat/Sun must be keyed to
    the Monday the league actually trades, since the runner reads the mandate via
    `current_week_start()` once that week begins.
    """
    return current_week_start() + timedelta(days=7)


def _economics_advisory(competitor_id: str) -> tuple[dict, str]:
    """F8: the competitor's OWN recent unit economics + an advisory string when
    its edge-to-cost is too thin. Advice only — the agent still chooses freely
    (league autonomy). Never raises; returns ({}, "") if analytics are unavailable."""
    try:
        econ = book_economics(competitor_filter=competitor_id, last_n=30)
    except Exception:
        return {}, ""
    advisory = ""
    if econ.n >= 10 and econ.realised_e2c < Decimal("3"):
        advisory = (
            "\n\nADVISORY — from YOUR OWN last-30-trade results (guidance, not a "
            f"rule; trade your edge): edge-to-cost {econ.realised_e2c} (<3) and cost "
            f"drag {econ.cost_drag_pct}% mean your moves were too small to clear "
            "the ~Rs13/trade round-trip cost. Net was a loser even when gross was "
            "flat. Consider higher-conviction, larger-move setups (fewer trades, "
            "wider targets) this week."
        )
    return econ.as_dict(), advisory


def _build_user_prompt(competitor: Competitor, wk_start: date | None = None) -> str:
    econ, advisory = _economics_advisory(competitor.id)
    snapshot = {
        "now_ist": datetime.now(IST).strftime("%Y-%m-%d %H:%M"),
        "week_start": (wk_start or current_week_start()).isoformat(),
        "max_symbols": MAX_MANDATE_SYMBOLS,
        "candidate_universe": list(TRADABLE_UNIVERSE),
        "your_recent_economics_last_30": econ,
    }
    return (
        "Plan your mandate for the week. Here is the candidate universe you may "
        "pick from and the week context.\n\n```json\n"
        + json.dumps(snapshot, indent=2, default=str)
        + "\n```"
        + advisory
    )


def _clean_universe(raw_universe: Any) -> list[str]:
    """Validate a backend's picks against TRADABLE_UNIVERSE.

    Upper-cases, drops anything outside the candidate set, de-duplicates while
    preserving order, and caps at MAX_MANDATE_SYMBOLS. Returns [] if nothing
    valid survives (callers fall back to a WATCHLIST slice).
    """
    tradable = set(TRADABLE_UNIVERSE)
    cleaned: list[str] = []
    if isinstance(raw_universe, list):
        for item in raw_universe:
            sym = str(item).strip().upper()
            if sym in tradable and sym not in cleaned:
                cleaned.append(sym)
            if len(cleaned) >= MAX_MANDATE_SYMBOLS:
                break
    return cleaned


def generate_mandate(competitor: Competitor,
                     wk_start: date | None = None) -> dict[str, Any]:
    """Ask the competitor's backend for its weekly mandate.

    `wk_start` only frames the prompt's week context (defaults to the current
    week); persistence keying is handled by the caller. Pass the upcoming Monday
    when planning ahead of the week (the weekend planner does this).

    Returns a dict with keys: universe (validated, non-empty), strategy_config,
    rationale, raw (the parsed backend payload), `fellback` (True if the backend
    produced no valid picks and a WATCHLIST slice was substituted), and `paused`
    (True if the backend was quota-paused and never called). The call is routed
    through the shared quota-gated path (helm.competition.backend.call_backend),
    so it respects per-backend quotas and is traced to `agent_invocations`
    (the quota / "how it thinks" ledger), exactly like a trading cycle.
    """
    persona = competitor.persona or "Balanced discretionary intraday trader."
    system = SYSTEM_PROMPT_TEMPLATE.format(
        persona=persona, max_symbols=MAX_MANDATE_SYMBOLS
    )
    user = _build_user_prompt(competitor, wk_start)

    call = call_backend(
        competitor_id=competitor.id, backend=competitor.backend,
        model=competitor.model, system=system, user=user, schema=MANDATE_SCHEMA,
    )
    raw: dict[str, Any] = call.parsed or {}
    if call.quota_blocked:
        insert_audit("competition_mandate", "quota_skip",
                     {"competitor_id": competitor.id, "backend": competitor.backend,
                      "reason": call.reason})
    elif not call.ok:
        insert_audit("competition_mandate", "llm_error",
                     {"competitor_id": competitor.id, "backend": competitor.backend,
                      "error": (call.error or "")[:500]})

    universe = _clean_universe(raw.get("universe"))
    fellback = not universe
    if fellback:
        universe = list(WATCHLIST[:FALLBACK_UNIVERSE_SIZE])

    strategy_config = raw.get("strategy_config")
    if not isinstance(strategy_config, dict):
        strategy_config = {}
    rationale = str(raw.get("rationale", ""))[:2000]

    return {
        "universe": universe,
        "strategy_config": strategy_config,
        "rationale": rationale,
        "raw": raw,
        "fellback": fellback,
        "paused": call.quota_blocked,
    }


def persist_mandate(
    competitor_id: str,
    universe: list[str],
    strategy_config: dict[str, Any],
    rationale: str,
    raw: dict[str, Any],
    *,
    wk_start: date | None = None,
) -> None:
    """Upsert one mandate row for (competitor_id, week_start)."""
    wk = wk_start or current_week_start()
    with conn() as c:
        c.execute(
            """
            INSERT INTO competitor_mandates
                (competitor_id, week_start, universe, strategy_config, rationale, raw)
            VALUES (%s, %s, %s::jsonb, %s::jsonb, %s, %s::jsonb)
            ON CONFLICT (competitor_id, week_start) DO UPDATE SET
                universe        = EXCLUDED.universe,
                strategy_config = EXCLUDED.strategy_config,
                rationale       = EXCLUDED.rationale,
                raw             = EXCLUDED.raw,
                created_at      = now()
            """,
            (competitor_id, wk, json.dumps(universe), json.dumps(strategy_config),
             rationale, json.dumps(raw)),
        )


def current_mandate(competitor_id: str, wk_start: date | None = None) -> dict | None:
    """This week's mandate row for a competitor, or None."""
    wk = wk_start or current_week_start()
    with conn() as c:
        return c.execute(
            """
            SELECT competitor_id, week_start, universe, strategy_config,
                   rationale, created_at
            FROM competitor_mandates
            WHERE competitor_id = %s AND week_start = %s
            """,
            (competitor_id, wk),
        ).fetchone()


def ensure_mandate(
    competitor: Competitor, *, force: bool = False, wk_start: date | None = None,
) -> dict[str, Any]:
    """Return this week's mandate, generating + persisting one if absent.

    Idempotent within a week: an existing mandate is returned untouched unless
    `force=True`, so re-running the weekly planner is cheap (no backend call).
    Returns a summary dict: {competitor_id, week_start, universe, rationale,
    created (bool), fellback (bool), paused (bool)}.

    If the backend is quota-paused, NO mandate is persisted (created=False,
    paused=True) — the runner's own WATCHLIST fallback covers the week and the
    next planning run can set the real mandate once quota frees up.
    """
    wk = wk_start or current_week_start()
    if not force:
        existing = current_mandate(competitor.id, wk)
        if existing:
            return {
                "competitor_id": competitor.id,
                "week_start": wk.isoformat(),
                "universe": list(existing["universe"] or []),
                "rationale": existing["rationale"] or "",
                "created": False,
                "fellback": False,
                "paused": False,
            }

    plan = generate_mandate(competitor, wk_start=wk)
    if plan["paused"]:
        return {
            "competitor_id": competitor.id,
            "week_start": wk.isoformat(),
            "universe": [],
            "rationale": "",
            "created": False,
            "fellback": False,
            "paused": True,
        }

    persist_mandate(
        competitor.id, plan["universe"], plan["strategy_config"],
        plan["rationale"], plan["raw"], wk_start=wk,
    )
    insert_audit(
        "competition_mandate", "planned",
        {"competitor_id": competitor.id, "backend": competitor.backend,
         "week_start": wk.isoformat(), "universe": plan["universe"],
         "fellback": plan["fellback"], "forced": force},
    )
    return {
        "competitor_id": competitor.id,
        "week_start": wk.isoformat(),
        "universe": plan["universe"],
        "rationale": plan["rationale"],
        "created": True,
        "fellback": plan["fellback"],
        "paused": False,
    }


def mandate_symbols(wk_start: date | None = None) -> set[str]:
    """Union of every ACTIVE competitor's current-week mandated symbols.

    Scoped to active competitors so paused/retired agents don't keep their
    symbols in the poller's workload.
    """
    wk = wk_start or current_week_start()
    syms: set[str] = set()
    with conn() as c:
        rows = c.execute(
            """
            SELECT m.universe
            FROM competitor_mandates m
            JOIN competitors comp ON comp.id = m.competitor_id
            WHERE m.week_start = %s AND comp.status = 'active'
            """,
            (wk,),
        ).fetchall()
    for r in rows:
        for s in (r["universe"] or []):
            sym = str(s).strip().upper()
            if sym:
                syms.add(sym)
    return syms


def extra_polling_symbols(wk_start: date | None = None) -> list[str]:
    """Mandated symbols that the house poller (WATCHLIST) does NOT already cover.

    This is exactly what scripts/poll_competition.py needs to poll — polling the
    house WATCHLIST again is left to poll_market.py, so there's no double work
    and the incumbent poller is untouched.
    """
    house = set(WATCHLIST)
    return sorted(s for s in mandate_symbols(wk_start) if s not in house)
