"""Weekly trading mandates for freestyle competitors.

Each freestyle competitor declares, once per week, the symbols it intends to
trade that week (its "mandate") plus an optional free-form strategy_config and a
plain-English rationale. The mandate is generated by the competitor's *own*
backend — its persona frames the pick — and persisted to `competitor_mandates`,
one row per (competitor, week_start = Monday).

The freestyle runner already reads this week's mandate via
`runner.competitor_universe()`, falling back to a WATCHLIST slice when none
exists, so a mandate is a pure enhancement — wiring this in is a drop-in.

A companion dynamic poller (`scripts/poll_competition.py`) polls the union of all
active mandates' symbols that lie *outside* the house WATCHLIST, so candle data
exists for whatever the competitors picked. The incumbent `poll_market.py` is
never touched.

$0 discipline: backend calls go through `helm.llm` (CLI mode — Claude
subscription / free gateways). No Anthropic API key is ever required.
"""

from __future__ import annotations

import json
import time
from datetime import date, datetime, timedelta
from typing import Any
from zoneinfo import ZoneInfo

from helm.competition.runner import Competitor, _log_invocation
from helm.config import TRADABLE_UNIVERSE, WATCHLIST
from helm.data.store import conn, insert_audit
from helm.llm import LLMError, complete_json

IST = ZoneInfo("Asia/Kolkata")

# A mandate may name at most this many symbols (the brief's "≤ ~15").
MAX_MANDATE_SYMBOLS = 15
# Deterministic fallback size when a backend returns nothing valid.
FALLBACK_UNIVERSE_SIZE = 8

MANDATE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "universe": {"type": "array", "items": {"type": "string"}},
        "strategy_config": {"type": "object"},
        "rationale": {"type": "string"},
    },
    "required": ["universe", "rationale"],
}

SYSTEM_PROMPT_TEMPLATE = """You are an autonomous intraday trader entering a new \
trading week in a live paper-trading league against other AI agents. You trade \
NSE equities and ETFs intraday (MIS, square off same day) from your own isolated \
cash wallet.

YOUR PERSONA / EDGE:
{persona}

TASK — pick your watchlist for the week ahead:
- Choose AT MOST {max_symbols} symbols you will focus on this week.
- Choose ONLY from the candidate universe given in the snapshot — symbols not in \
that list are not tradable on this account and will be ignored.
- Pick names that genuinely fit YOUR edge and that you expect to give clean, \
liquid intraday moves. Fewer, well-chosen names beat a long generic list.
- Optionally include a small `strategy_config` object of numeric parameters you \
want to remember and trade by this week (e.g. {{"stop_atr": 1.5, "max_trades_per_day": 4}}).
- Give a one-paragraph `rationale` explaining the picks in plain English.

OUTPUT — strict JSON only, no prose, no markdown fences:
{{"universe": ["SYM", "SYM", ...], "strategy_config": {{...}}, \
"rationale": "why these names fit my edge this week"}}"""


def week_start(d: date) -> date:
    """Monday of the week containing `d` (mandates are keyed by week_start)."""
    return d - timedelta(days=d.weekday())


def current_week_start() -> date:
    return week_start(datetime.now(IST).date())


def _build_user_prompt(competitor: Competitor) -> str:
    snapshot = {
        "now_ist": datetime.now(IST).strftime("%Y-%m-%d %H:%M"),
        "week_start": current_week_start().isoformat(),
        "max_symbols": MAX_MANDATE_SYMBOLS,
        "candidate_universe": list(TRADABLE_UNIVERSE),
    }
    return (
        "Plan your mandate for the week. Here is the candidate universe you may "
        "pick from and the week context.\n\n```json\n"
        + json.dumps(snapshot, indent=2, default=str)
        + "\n```"
    )


def _clean_universe(raw_universe: Any) -> list[str]:
    """Validate a backend's picks against TRADABLE_UNIVERSE.

    Upper-cases, drops anything outside the candidate set, de-duplicates while
    preserving order, and caps at MAX_MANDATE_SYMBOLS. Returns [] if nothing
    valid survives (callers fall back to a WATCHLIST slice).
    """
    tradable = set(TRADABLE_UNIVERSE)
    cleaned: list[str] = []
    if isinstance(raw_universe, list):
        for item in raw_universe:
            sym = str(item).strip().upper()
            if sym in tradable and sym not in cleaned:
                cleaned.append(sym)
            if len(cleaned) >= MAX_MANDATE_SYMBOLS:
                break
    return cleaned


def generate_mandate(competitor: Competitor) -> dict[str, Any]:
    """Ask the competitor's backend for its weekly mandate.

    Returns a dict with keys: universe (validated, non-empty), strategy_config,
    rationale, raw (the parsed backend payload), and `fellback` (True if the
    backend produced no valid picks and a WATCHLIST slice was substituted).
    The invocation is logged to `agent_invocations` (the quota / "how it thinks"
    ledger), exactly like a trading cycle.
    """
    persona = competitor.persona or "Balanced discretionary intraday trader."
    system = SYSTEM_PROMPT_TEMPLATE.format(
        persona=persona, max_symbols=MAX_MANDATE_SYMBOLS
    )
    user = _build_user_prompt(competitor)

    raw: dict[str, Any] = {}
    started = time.monotonic()
    try:
        raw = complete_json(
            system, user, schema=MANDATE_SCHEMA,
            model=competitor.model, backend=competitor.backend,
        )
        latency_ms = int((time.monotonic() - started) * 1000)
        _log_invocation(competitor, user, json.dumps(raw), latency_ms, ok=True, error=None)
    except LLMError as exc:
        latency_ms = int((time.monotonic() - started) * 1000)
        _log_invocation(competitor, user, None, latency_ms, ok=False, error=str(exc))
        insert_audit("competition_mandate", "llm_error",
                     {"competitor_id": competitor.id, "backend": competitor.backend,
                      "error": str(exc)[:500]})

    universe = _clean_universe(raw.get("universe"))
    fellback = not universe
    if fellback:
        universe = list(WATCHLIST[:FALLBACK_UNIVERSE_SIZE])

    strategy_config = raw.get("strategy_config")
    if not isinstance(strategy_config, dict):
        strategy_config = {}
    rationale = str(raw.get("rationale", ""))[:2000]

    return {
        "universe": universe,
        "strategy_config": strategy_config,
        "rationale": rationale,
        "raw": raw,
        "fellback": fellback,
    }


def persist_mandate(
    competitor_id: str,
    universe: list[str],
    strategy_config: dict[str, Any],
    rationale: str,
    raw: dict[str, Any],
    *,
    wk_start: date | None = None,
) -> None:
    """Upsert one mandate row for (competitor_id, week_start)."""
    wk = wk_start or current_week_start()
    with conn() as c:
        c.execute(
            """
            INSERT INTO competitor_mandates
                (competitor_id, week_start, universe, strategy_config, rationale, raw)
            VALUES (%s, %s, %s::jsonb, %s::jsonb, %s, %s::jsonb)
            ON CONFLICT (competitor_id, week_start) DO UPDATE SET
                universe        = EXCLUDED.universe,
                strategy_config = EXCLUDED.strategy_config,
                rationale       = EXCLUDED.rationale,
                raw             = EXCLUDED.raw,
                created_at      = now()
            """,
            (competitor_id, wk, json.dumps(universe), json.dumps(strategy_config),
             rationale, json.dumps(raw)),
        )


def current_mandate(competitor_id: str, wk_start: date | None = None) -> dict | None:
    """This week's mandate row for a competitor, or None."""
    wk = wk_start or current_week_start()
    with conn() as c:
        return c.execute(
            """
            SELECT competitor_id, week_start, universe, strategy_config,
                   rationale, created_at
            FROM competitor_mandates
            WHERE competitor_id = %s AND week_start = %s
            """,
            (competitor_id, wk),
        ).fetchone()


def ensure_mandate(
    competitor: Competitor, *, force: bool = False, wk_start: date | None = None,
) -> dict[str, Any]:
    """Return this week's mandate, generating + persisting one if absent.

    Idempotent within a week: an existing mandate is returned untouched unless
    `force=True`, so re-running the weekly planner is cheap (no backend call).
    Returns a summary dict: {competitor_id, week_start, universe, rationale,
    created (bool), fellback (bool)}.
    """
    wk = wk_start or current_week_start()
    if not force:
        existing = current_mandate(competitor.id, wk)
        if existing:
            return {
                "competitor_id": competitor.id,
                "week_start": wk.isoformat(),
                "universe": list(existing["universe"] or []),
                "rationale": existing["rationale"] or "",
                "created": False,
                "fellback": False,
            }

    plan = generate_mandate(competitor)
    persist_mandate(
        competitor.id, plan["universe"], plan["strategy_config"],
        plan["rationale"], plan["raw"], wk_start=wk,
    )
    insert_audit(
        "competition_mandate", "planned",
        {"competitor_id": competitor.id, "backend": competitor.backend,
         "week_start": wk.isoformat(), "universe": plan["universe"],
         "fellback": plan["fellback"], "forced": force},
    )
    return {
        "competitor_id": competitor.id,
        "week_start": wk.isoformat(),
        "universe": plan["universe"],
        "rationale": plan["rationale"],
        "created": True,
        "fellback": plan["fellback"],
    }


def mandate_symbols(wk_start: date | None = None) -> set[str]:
    """Union of every ACTIVE competitor's current-week mandated symbols.

    Scoped to active competitors so paused/retired agents don't keep their
    symbols in the poller's workload.
    """
    wk = wk_start or current_week_start()
    syms: set[str] = set()
    with conn() as c:
        rows = c.execute(
            """
            SELECT m.universe
            FROM competitor_mandates m
            JOIN competitors comp ON comp.id = m.competitor_id
            WHERE m.week_start = %s AND comp.status = 'active'
            """,
            (wk,),
        ).fetchall()
    for r in rows:
        for s in (r["universe"] or []):
            sym = str(s).strip().upper()
            if sym:
                syms.add(sym)
    return syms


def extra_polling_symbols(wk_start: date | None = None) -> list[str]:
    """Mandated symbols that the house poller (WATCHLIST) does NOT already cover.

    This is exactly what scripts/poll_competition.py needs to poll — polling the
    house WATCHLIST again is left to poll_market.py, so there's no double work
    and the incumbent poller is untouched.
    """
    house = set(WATCHLIST)
    return sorted(s for s in mandate_symbols(wk_start) if s not in house)
